// Compiles the framework-agnostic services in src/services (+ src/lib) to
// CommonJS under nodejs/services/ so the on-device Node server can require them.
//
// tsc does NOT copy .json files or rewrite the "@/*" path alias, so we:
//   1. compile with tsconfig.node.json (emits nodejs/services/{services,lib}/...)
//   2. copy src/data/*.json -> nodejs/services/data/ (for "@/data/*.json" imports)
//   3. write SENANG_LLM_* vars into nodejs/env-keys.js as a CommonJS module
//      so the on-device Node server has API keys in the APK (no .env on device).
// The "@/*" runtime alias is resolved by module-alias, registered in nodejs/index.js.

import { execSync } from 'node:child_process'
import { rmSync, mkdirSync, readdirSync, copyFileSync, existsSync, writeFileSync, readFileSync } from 'node:fs'
import { join } from 'node:path'

const OUT = 'nodejs/services'

rmSync(OUT, { recursive: true, force: true })
mkdirSync(OUT, { recursive: true })

console.log('[build-node] compiling services -> ' + OUT)
execSync('npx tsc --project tsconfig.node.json', { stdio: 'inherit' })

// Copy JSON data referenced via "@/data/*.json" value imports.
const DATA_SRC = 'src/data'
const DATA_OUT = join(OUT, 'data')
if (existsSync(DATA_SRC)) {
  mkdirSync(DATA_OUT, { recursive: true })
  let n = 0
  for (const f of readdirSync(DATA_SRC)) {
    if (f.endsWith('.json')) {
      copyFileSync(join(DATA_SRC, f), join(DATA_OUT, f))
      n++
    }
  }
  console.log(`[build-node] copied ${n} data json file(s) -> ${DATA_OUT}`)
}

// Read .env.local line by line, handling multiline values (Windows CRLF).
function loadDotEnv(path) {
  const map = {}
  if (!existsSync(path)) return map
  const text = readFileSync(path, 'utf8')
  const lines = text.split(/\r?\n/)
  for (let i = 0; i < lines.length; i++) {
    let line = lines[i]
    // Handle continuation lines (lines not containing '=' and not empty)
    while (i + 1 < lines.length && lines[i + 1].trim() && lines[i + 1].indexOf('=') === -1 && !lines[i + 1].trim().startsWith('#')) {
      i++
      line += lines[i].trim()
    }
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const eqIdx = trimmed.indexOf('=')
    if (eqIdx === -1) continue
    const key = trimmed.slice(0, eqIdx).trim()
    const val = trimmed.slice(eqIdx + 1).trim()
    if (key && val) map[key] = val
  }
  return map
}

const env = loadDotEnv('.env.local')
const keys = {}

// Collect SENANG_LLM_* vars (but NOT the actual API key values — those stay
// in .env.json which is gitignored; we just build the env-keys.js module that
// the nodejs server requires at startup).
for (const key of ['SENANG_LLM_KEYS', 'SENANG_LLM_MODEL', 'SENANG_LLM_FALLBACK', 'SENANG_ALLOW_ENV_LLM_KEYS', 'SENANG_ALLOW_KEY_SEED']) {
  if (env[key]) keys[key] = env[key]
}

if (Object.keys(keys).length > 0) {
  // Write as both .env.json (loaded by nodejs/index.js at startup) and
  // env-keys.js (CommonJS module — capacitor-nodejs may strip .json files).
  writeFileSync('nodejs/.env.json', JSON.stringify(keys, null, 2))
  const jsContent = `// Auto-generated by build-node.mjs — do not commit.
// Injects LLM keys into the Node.js runtime for the APK.
module.exports = ${JSON.stringify(keys, null, 2)};
`
  writeFileSync('nodejs/env-keys.js', jsContent)
  console.log(`[build-node] baked ${Object.keys(keys).length} env keys -> nodejs/.env.json + nodejs/env-keys.js`)
} else {
  console.warn('[build-node] WARNING: No SENANG_LLM_KEYS found in .env.local — APK Ask chat will be RAG-only')
}

console.log('[build-node] done')
